add exclude anime feature
quarckster/kodi.kino.pub pull request #120
Opened 2020-09-02 11:58 UTC by Limeone

2020-09-05 08:16 UTC, quarckster requested changes
Спасибо за PR. Мне непонятно, что будет, если в фильмах выбрать жанр аниме? Стоит ли исключить и выбор жанра тоже?

2020-09-05 08:16 UTC, quarckster commented on src/resources/lib/modeling.py
> +            del data["start_from"]
```python
start_from = int(data.pop("start_from", 0))
```

2020-09-05 08:16 UTC, quarckster commented on src/resources/lib/modeling.py
> +        none_anime_items = list(
non_anime_items

2020-09-05 08:24 UTC, Limeone commented on src/resources/lib/main.py
> +            response = plugin.items.get("items/{}".format(heading), data=data, exclude_anime=True)
Отфильтровывание аниме не на всех роутах, а только там где указано и если включено в настройках

2020-09-05 08:25 UTC, Limeone commented on src/resources/lib/modeling.py
> +        none_anime_items = list(
Ок

2020-09-05 08:28 UTC, Limeone commented
Аниме НЕ отфильтровывается если пользователь его намеренно ищет или открывает его через жанры. История: я не хочу видеть аниме в обновлениях и рекомендациях, но мои дети(жена) могут открыть их самостоятельно если нужно, не изменяя настроек плагина

2020-09-06 15:31 UTC, quarckster requested changes

2020-09-06 15:31 UTC, quarckster commented on src/resources/lib/main.py
> +        if plugin.settings.exclude_anime == "true":
```python
if plugin.settings.exclude_anime == "true" and "start_from" in pagination:
```

2020-09-06 15:31 UTC, quarckster commented on src/resources/lib/main.py
> +            response = plugin.items.get("items/{}".format(heading), data=data, exclude_anime=True)
@Limeone можно ли просто передавать значение аргумента `exclude_anime` из настроек, но только в тех роутах, где необходимо? Например:
```python
exclude_anime = plugin.settings.exclude_anime == "true"
response = plugin.items.get("items/{}".format(heading), data=data, exclude_anime=exclude_anime)
```
Тогда не нужно будет сравнивать `if self.exclude_anime and exclude_anime:` в `ItemsCollection.get`

2020-09-07 18:08 UTC, quarckster approved these changes

2020-09-07 18:09 UTC, merged