experimental speedtest feature
quarckster/kodi.kino.pub pull request #128
Opened 2020-09-10 10:32 UTC by Limeone

- Refactor settings sections

- Parse settings values types. Returns string, integer or boolean value

- Add speedtest experimental feature

- Give playable link depending on location set in settings

- Fix new request attempt on "Too many requests" response

2020-09-10 14:54 UTC, fallenfuzz commented
remark: if Germany selected as a server, first speed test to check that server and then other one 😊

2020-09-10 14:56 UTC, Limeone commented
> if Germany selected as a server, first speed test to check that server and then other one

в смысле проверять скорость только того сервера который выбран?

2020-09-10 15:38 UTC, fallenfuzz commented
ага, или только выбранного, или первый выбранный, а второй который есть еше в списке.

2020-09-10 15:40 UTC, Limeone commented
> ага, или только выбранного, или первый выбранный, а второй который есть еше в списке.

какую проблему этот подход решит?

2020-09-11 06:26 UTC, fallenfuzz commented
> > ага, или только выбранного, или первый выбранный, а второй который есть еше в списке.
> 
> какую проблему этот подход решит?

в целом не какую :) просто окуратненько

2020-09-11 06:46 UTC, quarckster commented
Этот PR надо разбить на несколько. Фича со спидтестом должна быть отдельно, настройки отдельно и т.д.

2020-09-11 07:45 UTC, quarckster requested changes

2020-09-11 07:45 UTC, quarckster commented on src/resources/lib/settings.py
> +                return value
Надеюсь, что в настройках только строки, инты и булевы типы :)

2020-09-11 07:45 UTC, quarckster commented on src/resources/lib/speedtest.py
> +        threading.Thread.__init__(self)
Лучше использовать super

2020-09-11 07:45 UTC, quarckster commented on src/resources/lib/speedtest.py
> +    def create(self, servers={}):
Не стоит мутабельные типы в значения по умолчанию ставить, это может привести к неожиданным последствиям. Лучше сделать так:
```python
def create(self, servers=None):
    self.servers = servers or {}
```

2020-09-11 07:45 UTC, quarckster commented on src/resources/lib/speedtest.py
> +    def create(self, servers={}):
Тоже самое.

2020-09-11 07:45 UTC, quarckster commented on src/resources/lib/speedtest.py
> +        global shutdown_event
Можно ли как-нибудь без глобальных переменных обойтись?

2020-09-11 07:47 UTC, Limeone commented on src/resources/lib/settings.py
> +                return value
именно так

2021-07-20 12:44 UTC, closed without merging