Proxy Support
quarckster/kodi.kino.pub pull request #325
Opened 2024-02-03 21:29 UTC by nikolaev-rd

# Добавлена поддержка прокси для запросов плагина к API Kino.pub

Не дождавшись ответа/реакции на тикет https://github.com/quarckster/kodi.kino.pub/issues/318, решил реализовать поддержку прокси самостоятельно.

## Как это работает

Плагин использует системные настройки прокси, которые задаются через меню: System → Internet Access

![image](https://github.com/quarckster/kodi.kino.pub/assets/24430718/0991ad71-b4eb-4a94-b602-888ef5c122fe)

Плагин проверяет, что системная настройка "Use proxy server" включена, далее распознает указанный тип прокси, и устанавливает этот прокси для всех запросов к API.

Для получения системных настроек написан отдельный класс — работает через JSONRPC API через метод [Settings.GetSettingValue](https://kodi.wiki/view/JSON-RPC_API/v13#Settings.GetSettingValue)

## Что умеет

Теперь плагин поддерживает прокси всех типов (с авторизацией и без):

* HTTP
* HTTPS
* SOCKS4
* SOCKS5

## Проверка

Протестировано на прокси HTTP (без авторизации) и SOCKS5 (с авторизацией).

2024-02-05 21:08 UTC, nikolaev-rd commented
На новом устройстве обнаружил еще место, где надо тоже добавить поддержку прокси (`auth.py`):

```
2024-02-04 21:07:11.955 T:906     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.URLError'>
                                                   Error Contents: <urlopen error [Errno 104] Connection reset by peer>
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
                                                     File "/usr/lib/python3.11/http/client.py", line 1282, in request
                                                     File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
                                                     File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
                                                     File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
                                                     File "/usr/lib/python3.11/http/client.py", line 975, in send
                                                     File "/usr/lib/python3.11/http/client.py", line 1454, in connect
                                                     File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
                                                     File "/usr/lib/python3.11/ssl.py", line 1075, in _create
                                                     File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
                                                   ConnectionResetError: [Errno 104] Connection reset by peer

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                       plugin.run()
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 88, in run
                                                       self.routing.dispatch(self.path)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 71, in dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/main.py", line 86, in login
                                                       plugin.auth.get_token()
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 218, in get_token
                                                       self._activate()
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 204, in _activate
                                                       resp = self._get_device_code()
                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 127, in _get_device_code
                                                       resp = self._make_request(payload)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/video.kino.pub/resources/lib/auth.py", line 85, in _make_request
                                                       response = urllib.request.urlopen(
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
                                                     File "/usr/lib/python3.11/urllib/request.py", line 519, in open
                                                     File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
                                                     File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
                                                     File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
                                                     File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
                                                   urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
                                                   -->End of Python script error report<--
```

2024-02-06 07:13 UTC, quarckster requested changes

2024-02-06 07:13 UTC, quarckster commented on src/resources/lib/xbmc_settings.py
> +        super().__init__()
Здесь это не нужно.

2024-02-06 07:14 UTC, quarckster commented
Спасибо за PR :heart:

2024-02-06 15:41 UTC, nikolaev-rd commented on requirements_dev.in
> +PySocks
Да, это я понял когда на чистую ставил плагин.
Добавил.

2024-02-06 15:43 UTC, nikolaev-rd commented on src/resources/lib/xbmc_settings.py
> +        super().__init__()
Я использую это для логов:

```python
self.plugin.logger.debug(f"Try to get system setting: {setting_id}")
```

2024-02-06 15:47 UTC, quarckster commented on src/resources/lib/xbmc_settings.py
> +        super().__init__()
> Я использую это для логов:
> 
> ```python
> self.plugin.logger.debug(f"Try to get system setting: {setting_id}")
> ```

Класс не наследуется ни от чего, так что нет смысла вызвать родительский `__init__()`. `self.plugin.logger` будет работать и без этого, поскольку `plugin` передаётся параметром при инициализации экземпляра класса.

2024-02-06 16:24 UTC, nikolaev-rd commented on src/resources/lib/xbmc_settings.py
> +    def is_correct(self):
Добавил ✔️

2024-02-06 17:14 UTC, nikolaev-rd commented on src/resources/lib/xbmc_settings.py
> +        super().__init__()
IDE так не видит properties для логгера, но да ладно.

2024-02-06 17:16 UTC, nikolaev-rd commented on src/resources/lib/xbmc_settings.py
> +        super().__init__()
Убрал всё лишнее

2024-02-06 17:19 UTC, nikolaev-rd commented on src/resources/lib/xbmc_settings.py
> +        return True if self.enabled and len(self.host) > 3 and self.port > 0 else False
> и почему больше 3?

потому что не бывает домена меньше 2 букв + точка + хотя бы 1 буква = 4, то больше 3.

> И вообще мне кажется бесполезная проверка. Что там юзер с прокси у себя наворотил не забота плагина.

Можно переложить это на пользователя, но я всегда исхожу из мысли, что потом мне это дебажить, и если там будет моя проверка и защита от дурака, наверняка всем будет лучше.

2024-02-06 17:21 UTC, nikolaev-rd commented on src/resources/lib/xbmc_settings.py
> +        return True if self.enabled and len(self.host) > 3 and self.port > 0 else False
В противном случае надо будет понять как некорректную настройку обработает компонент, которому я её передаю, и надеятся что оттуда вылетит что-то осознанное и понятное в ошибке, если она (ошибка) вобще будет.

2024-02-06 19:23 UTC, quarckster commented on src/resources/lib/client.py
> +            socket.socket = socks.socksocket  # type: ignore[misc]
Мне не очень нравится этот манкипатчинг стандартной либы, неужели по-другому нельзя?

2024-02-06 19:24 UTC, quarckster commented on src/resources/lib/xbmc_settings.py
> +        super().__init__()
Всё как раз убирать не надо было, а только `super().__init__()`.

2024-02-06 19:30 UTC, quarckster commented on src/resources/lib/client.py
> +        proxy_settings = XbmcProxySettings(self.plugin)
Инициализацию нужно сделать в `src/resources/lib/plugin.py` в `__init__()` методе класса `Plugin`:

```python
def __init__(self) -> None:
    proxy_settings = XbmcProxySettings(self)
```

Потом вызывать можно будет через `self.plugin.proxy_settings`.

2024-02-06 19:31 UTC, quarckster commented
Ещё нужно разобраться с тестами, ни один не проходит.

2024-02-06 20:31 UTC, nikolaev-rd commented on src/resources/lib/client.py
> +        proxy_settings = XbmcProxySettings(self.plugin)
Вроде сделал: https://github.com/quarckster/kodi.kino.pub/pull/325/commits/100a66524cab277ad47bd9a2513b441c5c4ba510

2024-02-06 20:57 UTC, nikolaev-rd commented on src/resources/lib/client.py
> +            socket.socket = socks.socksocket  # type: ignore[misc]
В каком плане: тернарник этот раздражает? Просто чтобы логику сверху не накручивать отдельно на случай с авторизацией и без, каких-то хендлеров не нашел.

Хотя может прокатит вот так тоже и для socks:

```
proxy_handler = urllib.request.ProxyHandler({
    'http': 'socks5://www.example.com:3128/',
    'https': 'socks5://www.example.com:3128/',
})
proxy_auth_handler = urllib.request.ProxyBasicAuthHandler()
proxy_auth_handler.add_password('realm', 'host', 'username', 'password')
```

2024-02-07 21:13 UTC, nikolaev-rd commented
> Ещё нужно разобраться с тестами, ни один не проходит.

Я вот даже не знаю, че с этими тестами. Это точно я сломал?
`Error: no pod with name or ID kodipod found: no such pod`

2024-02-08 14:58 UTC, quarckster commented on src/resources/lib/client.py
> +            socket.socket = socks.socksocket  # type: ignore[misc]
Нет, мне не нравится, конкретно эта строчка:

```python
socket.socket = socks.socksocket
```

2024-02-08 15:03 UTC, quarckster commented on src/resources/lib/xbmc_settings.py
> +        return True if self.username and self.password else False
```python
return self.username and self.password
```

2024-02-08 19:01 UTC, nikolaev-rd commented on src/resources/lib/xbmc_settings.py
> +        return True if self.username and self.password else False
Не, так строку возвращает, даже pre-commit тест ругается. Ну или я чет не понимаю.

2024-02-09 06:22 UTC, quarckster commented on src/resources/lib/xbmc_settings.py
> +        return True if self.username and self.password else False
Тогда так можно:

```python
return bool(self.username and self.password)
```

но не обязательно.

2024-02-09 06:24 UTC, quarckster commented
> > Ещё нужно разобраться с тестами, ни один не проходит.
> 
> Я вот даже не знаю, че с этими тестами. Это точно я сломал? `Error: no pod with name or ID kodipod found: no such pod`

С тестами всё нормально, вот недавний PR, в котором тесты прошли https://github.com/quarckster/kodi.kino.pub/pull/323

2024-02-10 22:31 UTC, nikolaev-rd commented on src/resources/lib/client.py
> +            socket.socket = socks.socksocket  # type: ignore[misc]
Вобщем, походу все так делают в случае urllib (до 3-й версии) + SOCKS, потому что там нет поддержки socks.

В случае [urllib3 уже всё есть](https://urllib3.readthedocs.io/en/stable/advanced-usage.html#socks-proxies):

```python
from urllib3.contrib.socks import SOCKSProxyManager

proxy = SOCKSProxyManager("socks5h://localhost:8889/")
proxy.request("GET", "https://google.com/")
```

Делать свой сабкласс от `ProxyHandler()` и, по сути, писать свой аналог реализации из urllib3 — даже не знаю, кажется слишком.

2024-02-10 22:58 UTC, nikolaev-rd commented
> На новом устройстве обнаружил еще место, где надо тоже добавить поддержку прокси (`auth.py`):

@quarckster смотрю как попроще сюда тоже добавить поддержку прокси, потому что иначе нельзя сделать активацию устройства, и ощущение что можно унаследовать `KinoPubClient` + подпилить потом часть методов в классе `Auth`.
Иначе придется копипастить код для прокси, или выносить его еще куда-нить, чтобы потом в двух местах использовать.

Что скажешь?

2024-02-20 18:51 UTC, quarckster commented
> @quarckster подскажи, где мне еще надо прописать этот модуль?
Необходимо сюда https://github.com/quarckster/kodi.kino.pub/tree/master/tests/data/addons положить этот плагин https://kodi.tv/addons/nexus/script.module.pysocks/

2024-02-20 22:14 UTC, nikolaev-rd commented
Положил, но ошибка та же:
```
                                                     File "/home/kodi/.kodi/addons/video.kino.pub/resources/lib/client.py", line 17, in <module>
                                                       import socks
                                                   ModuleNotFoundError: No module named 'socks'
                                                   -->End of Python script error report<--
```

2024-02-22 15:38 UTC, amironofff commented
У меня проблема, как в тикете 318. Поддержка кинопаба (очень добрые люди) отправила сюда. Я почитал эти тикеты, и как в меме "ничего не понял, но очень интересно". Есть где-нибудь инструкция как починить? Или нужно искать где-то прокси и просто прописывать его в настройках Kodi?

2024-02-22 16:15 UTC, quarckster commented
> У меня проблема, как в тикете 318. Поддержка кинопаба (очень добрые люди) отправила сюда. Я почитал эти тикеты, и как в меме "ничего не понял, но очень интересно". Есть где-нибудь инструкция как починить? Или нужно искать где-то прокси и просто прописывать его в настройках Kodi?

Поддержка прокси ещё не реализована. Постараюсь помочь с этим пулл реквестом.

2024-02-22 16:21 UTC, amironofff commented
> > У меня проблема, как в тикете 318. Поддержка кинопаба (очень добрые люди) отправила сюда. Я почитал эти тикеты, и как в меме "ничего не понял, но очень интересно". Есть где-нибудь инструкция как починить? Или нужно искать где-то прокси и просто прописывать его в настройках Kodi?
> 
> Поддержка прокси ещё не реализована. Постараюсь помочь с этим пулл реквестом.

Спасибо огромное! Очень жду! Совсем недавно нашел как победить фризы через InputStream. И тут эта проблема. Спасибо заранее еще раз!

2024-02-24 11:11 UTC, nikolaev-rd commented
@quarckster похоже тесты не проходят по коммитам от меня, а по твоим коммитам работают. Видимо чето с правами.

2024-02-24 11:39 UTC, nikolaev-rd reviewed
👍🏻

2024-02-24 11:41 UTC, quarckster commented
Я ещё потетсирую изменения у себя и хотел бы добавить тесты.

2024-02-24 12:28 UTC, nikolaev-rd commented
> Я ещё потетсирую изменения у себя и хотел бы добавить тесты.

На RPi2 и прокси через http (без авторизации) / socks (с авторизацией) я проверил — работает.

2024-02-25 13:36 UTC, amironofff commented
У меня не заработало на SOCK4.
Вот кусок лога - на сертификаты ругается:
2024-02-25 16:29:52.085 T:734     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.URLError'>
                                                   Error Contents: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)>
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
                                                       h.request(req.get_method(), req.selector, req.data, headers,
                                                     File "/usr/lib/python3.9/http/client.py", line 1255, in request
                                                       self._send_request(method, url, body, headers, encode_chunked)
                                                     File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
                                                       self.endheaders(body, encode_chunked=encode_chunked)
                                                     File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
                                                       self._send_output(message_body, encode_chunked=encode_chunked)
                                                     File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
                                                       self.send(msg)
                                                     File "/usr/lib/python3.9/http/client.py", line 950, in send
                                                       self.connect()
                                                     File "/usr/lib/python3.9/http/client.py", line 1424, in connect
                                                       self.sock = self._context.wrap_socket(self.sock,
                                                     File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                     File "/usr/lib/python3.9/ssl.py", line 1040, in _create
                                                       self.do_handshake()
                                                     File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                       plugin.run()
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 90, in run
                                                       self.routing.dispatch(self.path)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 71, in dispatch
                                                       view_func(**kwargs)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/main.py", line 151, in items
                                                       response = plugin.items.get(f"items/{heading}", data=data, exclude_anime=exclude_anime)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/modeling.py", line 42, in get
                                                       resp = self.plugin.client(endpoint).get(data=data)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/client.py", line 214, in get
                                                       return self._make_request(request)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/client.py", line 203, in _make_request
                                                       response = self.opener.open(request, timeout=TIMEOUT)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 517, in open
                                                       response = self._open(req, data)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
                                                       result = self._call_chain(self.handle_open, protocol, protocol +
                                                     File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
                                                       result = func(*args)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
                                                       return self.do_open(http.client.HTTPSConnection, req,
                                                     File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
                                                       raise URLError(err)
                                                   urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)>
                                                   -->End of Python script error report<--
                                                   
2024-02-25 16:29:52.202 T:733     error <general>: GetDirectory - Error getting plugin://video.kino.pub/items/all/fresh/
2024-02-25 16:29:52.218 T:559     error <general>: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/items/all/fresh/) failed

2024-02-25 17:26 UTC, nikolaev-rd commented
> У меня не заработало на SOCK4. Вот кусок лога - на сертификаты ругается
Тут что-то с прокси — используется самоподписной сертификат, что все либы считают неправильным (я тут с ними согласен). Вот такой попробуй (чисто для теста, это рандомная прокся из интернетов): `103.148.57.103:30001`

2024-02-25 20:36 UTC, amironofff commented
Попробовал с предложенным прокси - результат такой же, но есть отличие визуальное: после нажатие на кнопку "Закладки" ожидание сильно дольше до появления ошибки. 
В логах опять ругается на сертификат:
_2024-02-25 23:14:34.241 T:745     error <general>: GetDirectory - Error getting plugin://video.kino.pub/bookmarks/
2024-02-25 23:14:34.250 T:546     error <general>: CGUIMediaWindow::GetDirectory(plugin://video.kino.pub/bookmarks/) failed
2024-02-25 23:15:07.436 T:546     error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-02-25 23:15:49.925 T:793     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.URLError'>
                                                   Error Contents: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)>
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
                                                       h.request(req.get_method(), req.selector, req.data, headers,
                                                     File "/usr/lib/python3.9/http/client.py", line 1255, in request
                                                       self._send_request(method, url, body, headers, encode_chunked)
                                                     File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
                                                       self.endheaders(body, encode_chunked=encode_chunked)
                                                     File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
                                                       self._send_output(message_body, encode_chunked=encode_chunked)
                                                     File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
                                                       self.send(msg)
                                                     File "/usr/lib/python3.9/http/client.py", line 950, in send
                                                       self.connect()
                                                     File "/usr/lib/python3.9/http/client.py", line 1424, in connect
                                                       self.sock = self._context.wrap_socket(self.sock,
                                                     File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                     File "/usr/lib/python3.9/ssl.py", line 1040, in _create
                                                       self.do_handshake()
                                                     File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/addon.py", line 6, in <module>
                                                       plugin.run()
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/plugin.py", line 90, in run
                                                       self.routing.dispatch(self.path)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/routing.py", line 71, in dispatch
                                                       view_func(**kwargs)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/main.py", line 319, in bookmarks
                                                       response = plugin.client("bookmarks").get()
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/client.py", line 214, in get
                                                       return self._make_request(request)
                                                     File "/home/osmc/.kodi/addons/video.kino.pub/resources/lib/client.py", line 203, in _make_request
                                                       response = self.opener.open(request, timeout=TIMEOUT)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 517, in open
                                                       response = self._open(req, data)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
                                                       result = self._call_chain(self.handle_open, protocol, protocol +
                                                     File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
                                                       result = func(*args)
                                                     File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
                                                       return self.do_open(http.client.HTTPSConnection, req,
                                                     File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
                                                       raise URLError(err)
                                                   urllib.error.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)>
                                                   -->End of Python script error report<--_
         


И еще интересный момент - после проверки предложенного хоста с портом на все типы прокси, которые есть в Kodi, я выключил прокси и о чудо - все заработало. Проверил на "Закладки" - там провалился в папку и запустил фильм, и на "New", оттуда тоже фильм запустился.

2024-02-27 21:43 UTC, nikolaev-rd commented
> Попробовал с предложенным прокси - результат такой же, но есть отличие визуальное: после нажатие на кнопку "Закладки" ожидание сильно дольше до появления ошибки.

Странно, у меня работает (со второго раза запрос прошел, прокся эта рандомная — явно медленная, но всё же). В настройках так делал:
```
Type: SOCKS4A
Host: 103.148.57.103
Port: 30001
```

Опять же, советую купить где-нить прокси/vpn, чтобы не страдать с рандомными прокси из интернетов, где непонятно что на них с трафиком происходит потом.

Ошибка
```
urllib.error.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)>
```
возникает в случаях, когда к http-прокси пытаются обращаться как к https-прокси (на самом деле там должен быть http + TLS), похоже тут всё тоже верно.

2024-03-09 16:52 UTC, merged

2024-03-27 22:42 UTC, abdullasharapov commented
> # Добавлена поддержка прокси для запросов плагина к API Kino.pub
> 
> Не дождавшись ответа/реакции на тикет #318, решил реализовать поддержку прокси самостоятельно. Resolves #318
> ## Как это работает
> 
> Плагин использует системные настройки прокси, которые задаются через меню: System → Internet Access
> 
> ![image](https://private-user-images.githubusercontent.com/24430718/302062865-0991ad71-b4eb-4a94-b602-888ef5c122fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NzcwMzMsIm5iZiI6MTcxMTU3NjczMywicGF0aCI6Ii8yNDQzMDcxOC8zMDIwNjI4NjUtMDk5MWFkNzEtYjRlYi00YTk0LWI2MDItODg4ZWY1YzEyMmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDIxNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ODgzMzVjMDk5YmE1NTdiZDZhNzhhYmEyYTk1YjFkY2E1NGQyNzc0MGFjZmMzZDFmNDZmYjJkOWZiODMyOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qBxGBVrtklHpuvVspu7ISnKBLUVuikYYUFElGIdOC8)
> 
> Плагин проверяет, что системная настройка "Use proxy server" включена, далее распознает указанный тип прокси, и устанавливает этот прокси для всех запросов к API.
> 
> Для получения системных настроек написан отдельный класс — работает через JSONRPC API через метод [Settings.GetSettingValue](https://kodi.wiki/view/JSON-RPC_API/v13#Settings.GetSettingValue)
> ## Что умеет
> 
> Теперь плагин поддерживает прокси всех типов (с авторизацией и без):
> 
>     * HTTP
> 
>     * HTTPS
> 
>     * SOCKS4
> 
>     * SOCKS5
> 
> 
> ## Проверка
> 
> Протестировано на прокси HTTP (без авторизации) и SOCKS5 (с авторизацией).
Подскажите по деталям. Все запросы к API теперь заворачиваются через прокси. А как дело обстоит с контентом? Контент тянется с другого адреса?
Ну и в целом, использование прокси на системном уровне коди вероятно повлияет на то, что остальные приложения будут гонять трафик через проксю. Не рассматриваете возможность использования прокси лишь на уровне аддона, т.е. добавить соответствующий пункт в меню аддона?

2024-03-27 22:59 UTC, nikolaev-rd commented
> Подскажите по деталям. Все запросы к API теперь заворачиваются через прокси. А как дело обстоит с контентом? Контент тянется с другого адреса?

Да, видео/картинки стримятся напрямую, через прокси идут только запросы к API Кинопаба.

> Ну и в целом, использование прокси на системном уровне коди вероятно повлияет на то, что остальные приложения будут гонять трафик через проксю.

Такое возможно, но из моей практики — редко какой аддон умеет подхватывать системную прокси. 

> Не рассматриваете возможность использования прокси лишь на уровне аддона, т.е. добавить соответствующий пункт в меню аддона?

По идеи можно сделать, но мне показалось что системные настройки уже есть, наоборот так проще — настроил в одном месте, а не в каждом плагине каждый раз. К тому же в тех плагинах, которые умеют в системную прокси, как правило в настройках плагина можно вкл/выкл использование прокси, либо указать свою прокси в плагине.